module.exports = [
'Your head no dey house - na only breeze dey blow inside.',
'If sense was common, you no go still dey find am.',
'Your papa use leg take born you, na why you dey waka sideways.',
'Person wey dey chop rat leftover, na you be that.',
'Your mama born you finish con regret say she waste 9 months.',
'You be the reason your family no dey do reunion.',
'Olodo! Even goat sabi pass you for thinking.',
'Your brain na small size, e no fit carry two thoughts at once.',
'Abeg shift, your matter no dey important.',
'You wey your shadow dey shame to follow you.',
'Werey! If madness dey sell, you go buy wholesale.',
'Your generation na mistake wey nature make.',
'You open mouth dey talk but brain no dey inside - na only breeze.',
'Ode! Your sense dey miss since 1999.',
'Agbaya! You don old finish but sense still dey nursery.',
'If foolishness was job, you go be manager.',
'Your head correct? Or na only skull dey empty inside?',
'Person wey dey fail WAEC 10 times dey talk - na you.',
'You be the reason God created backup plans.',
'Your family tree na just one straight line - no branch, no root.',
'See this one wey even mosquito dey reject.',
'If you were a phone, you go be Nokia 3310 - old, useless, no update.',
'You dey breathe but you no dey alive.',
'Your brain na like Lagos traffic - nothing dey move.',
'Na so-so nonsense dey come out from your mouth like NEPA wire.',
'You be like MTN network - you dey waka but you no dey reach anywhere.',
'Even your reflection dey avoid you for mirror.',
'Agbero! Na only you know how to make people regret say dem meet you.',
'If nonsense was an award, you go win Nobel prize.',
'Your sense na like fuel for Nigeria - e don finish.',
'You fail everything wey you try - even sleep sef.',
'Your name dey fear people for dreams.',
'Person wey no sabi talk dey talk pass you - na the goat wey dey bleat all day.',
'You be the reason villages dey use "abeg" as warning.',
'Oloshi! Your level na "start over" for every aspect of life.',
'If brain was food, you go dey hungry till today.',
'Your papa wey born you - e try. But e fail.',
'You be definition of "wasted potential" - with a capital W.',
'Even your own shoe dey plan to run away.',
'Oloriburuku! Your head no correct since birth.',
'If your sense was money, you go still dey owe.',
'Your face na the only thing wey night dey fear.',
'You dey talk grammar but your English no reach primary 2.',
'Person wey dey fail life exam dey talk - you be the sample.',
'You be like expired milk - nobody want you but you no dey go.',
'Agbaya! You don pass maturity but you no reach sense.',
'Your life na definition of "close but never".',
'If goat get sense, e go deny say e know you.',
'Your mouth na like broken pipe - nonsense dey flow non-stop.',
'You be reason people dey lock their doors - not for thief, for you.',
'Your shadow don apply for transfer.',
'Ode! Your brain dey work overtime but e never produce anything.',
'Your birth na mistake wey nobody own up to.',
'You dey exist but you no dey live.',
'Even your own hair dey try run from your head.',
'If suffering was a brand, you go be ambassador.',
'Your future don pass tense - na "never was".',
'Person wey even cockroach dey avoid - na you be that.',
'You dey talk but your voice no dey carry weight - like empty drum.',
'Werey! If your brain was land, e go be desert.',
'Your papa try - but he should have tried harder.',
'You be the reason family planning was invented.',
'Your sense na like NEPA light - e dey come, e dey go.',
'Olodo! If school was for free, you go still fail.',
'Your mouth na like pit toilet - anything dey come out.',
'You be like bad belle - bitter for no reason.',
'Your face na reason babies dey cry.',
'If ugliness was a sin, you go be in hell.',
'Person wey dey collect leftover from dog - na your level.',
'Oloriburuku! Your head na like scattered egg - no shape, no sense.',
'You be example wey teachers use to warn students.',
'Your life story na short - no beginning, no middle, no end.',
'Even your own brain dey reject you.',
'If nonsense paid salary, you go be millionaire.',
'Your presence dey drain people energy.',
'Agbaya! You don reach 40 but your sense still dey teething.',
'You be like expired ATM card - no value, no use.',
'Your head no correct - I don check am twice.',
'Oloshi! Your level na "beginner" for everything.',
'If failure was a person, e go be you.',
'Your name dey make people remember why dem no like you.',
'You be the reason "warning" signs exist.',
'Person wey even goat dey laugh at - you be that.',
'Your sense don travel go other country - e never return.',
'You be like broken record - same nonsense, repeat.',
'If uselessness was a job, you go work double shift.',
'Your birth na the only L your mama collect.',
'You be definition of "almost" - almost smart, almost useful, almost human.',
'Your shadow self dey pretend say e no know you.',
'Ode! Your brain dey sleep even when you dey awake.',
'You be like expired recharge card - no value, no use.',
'Person wey dey beg goat for direction dey talk - na you.',
'Your life na like bad movie - long, boring, no ending.',
'You be example of "how not to be".',
'Even your own reflection dey look away.',
'Your sense na borrowed - and the lender don collect am back.',
'You dey chop but you no dey grow - na waste of resources.',
'Person wey dey lose bet to chicken - you be that.',
'Your future don expired before e start.',
'Oloshi! Your head na only for decoration - no brain inside.',
'Your papa born you - but e no born your sense.',
'You be reason village people dey lock gate for night.',
'Even your own teeth dey plan to leave your mouth.',
'If stupid was a medal, you go get platinum.',
'Your brain na like empty tank - nothing dey inside.',
'You be the reason "abeg no vex" was invented.',
'Your face na the reason mirror dey crack.',
'Person wey even rat dey disrespect - you be that.',
'Your sense na imported from nowhere.',
'You dey exist but e no make sense.',
'If your brain was land, e go be no-man land.',
'Your mouth na the reason silence was invented.',
'You be like wrong number - no reason to answer.',
'Ode! Your brain dey on holiday - since birth.',
'Your value na zero - and even zero get value pass you.',
'Person wey even thief dey reject - you be that.',
'Your life na example wey people use for "no be like this".',
'You be like bad weather - everybody dey hope say you go pass.',
'Even your own shadow dey ask for refund.',
'Your name na the reason people fear for night.',
'If nonsense was a language, you go be native speaker.',
'Person wey even goat dey use as bad example - you be that.',
'Your brain na like Lagos traffic - permanent hold-up.',
'You be like expired food - nobody want you but you no dey go.',
'Olodo! If education was free, you go still refuse am.',
'Your face na the reason camera dey fail.',
'Person wey dey beg for leftover from rat - you be that.',
'Your sense na like dry river - no water, no life.',
'You be the reason warning tape was made.',
'If failure was a person, e go send you birthday card.',
'Your life na example wey should be deleted from history.',
'Even your own hair dey beg for transfer.',
'You be like stale bread - hard, useless, unwanted.',
'Your voice na like noise - nothing meaningful.',
'Person wey even cockroach dey run from - you be that.',
'Your brain dey work but e no dey produce result.',
'You be like bad signal - no connection, no use.',
'If uselessness was a sport, you go be world champion.',
'Person wey even mad person dey fear - you be that.',
'Your birth na the reason your papa run comot.',
'Your head na like empty box - nothing inside.',
'You be the reason no-try-this-at-home was invented.',
'If foolishness was a job, you go work overtime.',
'Your future don expire before e start.',
'Person wey even dog dey run from - you be that.',
'Your sense na like bad fuel - useless, destructive.',
'You be like broken mirror - useless and dangerous.',
'If stupidity was an exam, you go fail with A+.',
'Your name na reason people dey fear for night.',
'Person wey even goat dey reject - you be that.',
'You dey live but you no dey alive - na only breathing dey happen.',
'Your existence na the reason good people dey scarce.',
'Even your own reflection dey beg for change.',
'If you were a product, you go be recalled.',
'Your brain na the reason village people dey fear for science.',
'Person wey even rat dey ignore - you be that.',
'Your life na the reason God created delete button.',
'You be like expired contract - no value, no renewal.',
'If nonsense was water, you go be ocean.',
'Person wey even madman dey avoid - you be that.'
]
